spring:
  cloud:
    gateway:
      routes:
        - id: msvc-shoppingcart
          uri: lb://msvc-shoppingcart
          predicates:
            - Path=/api/shoppingcart/**
          filters:
            - StripPrefix=2
        - id: getial
          uri: lb://getial
          predicates:
            - Path=/api/getial/**
          filters:
            - StripPrefix=2