apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-shoppingcart
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: msvc-shoppingcart
  template:
    metadata:
      labels:
        app: msvc-shoppingcart
    spec:
      containers:
        - name: shoppingcart
          image: carloshot007/msvc-shoppingcart
          ports:
            - containerPort: 8002
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: msvc-shoppingcart
                  key: port
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: msvc-shoppingcart
                  key: db_host
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: msvc-shoppingcart
                  key: database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: msvc-shoppingcart
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: msvc-shoppingcart
                  key: password
            - name: MSVC_USERS_URL
              valueFrom:
                configMapKeyRef:
                  name: msvc-shoppingcart
                  key: msvc_users_url
            - name: MSVC_IMAGES_URL
              valueFrom:
                configMapKeyRef:
                  name: msvc-shoppingcart
                  key: msvc_images_url