version: '3.9'
services:
  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - '5532:5432'
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: msvc_shoppingcart
    volumes:
      - data-postgres:/var/lib/postgres/data
    networks:
      - imagehub
    restart: always

  msvc-shoppingcart:
    container_name: msvc-shoppingcart
    image: carloshot007/msvc-shoppingcart:latest
    build:
      context: ./
      dockerfile: ./msvc-shoppingcart/Dockerfile
    ports:
      - '8002:8002'
    # env_file: ./msvc-shoppingcart/.env
    environment:
      PORT: 8002
      DB_HOST: postgres14:5432
      DB_DATABASE: msvc_shoppingcart
      DB_USERNAME: postgres
      DB_PASSWORD: root
      MSVC_USERS_URL: msvc-users:8002
      MSVC_IMAGES_URL: msvc-images:8002
    networks:
      - imagehub
    depends_on:
      - postgres14
    restart: always

volumes:
  data-postgres:
    name: data-postgres

networks:
  imagehub:
    name: imagehub
