apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard # It's possible to see in `kubectl get sc`
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/postgres/data
    type: DirectoryOrCreate