apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-shoppingcart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-shoppingcart
  template:
    metadata:
      labels:
        app: msvc-shoppingcart
    spec:
      containers:
        - name: shoppingcart
          image: carloshot007/msvc-shoppingcart:latest
          ports:
            - containerPort: 8002
          env:
            - name: PORT
              # valueFrom:
              #   configMapKeyRef:
              #     name: msvc-shoppingcart
              #     key: port
              value: "8002"
            - name: DB_HOST
              # valueFrom:
              #   configMapKeyRef:
              #     name: msvc-shoppingcart
              #     key: db_host
              value: "postgres14:5432"
            - name: DB_DATABASE
              # valueFrom:
              #   configMapKeyRef:
              #     name: msvc-shoppingcart
              #     key: database
              value: "msvc_shoppingcart"
            - name: DB_USERNAME
              # valueFrom:
              #   configMapKeyRef:
              #     name: msvc-shoppingcart
              #     key: username
              value: "postgres"
            - name: DB_PASSWORD
              # valueFrom:
              #   configMapKeyRef:
              #     name: msvc-shoppingcart
              #     key: password
              value: "root"
            - name: MSVC_USERS_URL
              # valueFrom:
              #   configMapKeyRef:
              #     name: msvc-shoppingcart
              #     key: msvc_users_url
              value: "msvc-users:8001"
            - name: MSVC_IMAGES_URL
              # valueFrom:
              #   configMapKeyRef:
              #     name: msvc-shoppingcart
              #     key: msvc_images_url
              value: "msvc-images:8003"

---
apiVersion: v1
kind: Service
metadata:
  name: msvc-shoppingcart
spec:
  type: LoadBalancer
  ports:
    - port : 8002
      protocol: TCP
      targetPort: 8002
  selector:
    app: msvc-shoppingcart