apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-shoppingcart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-shoppingcart
  template:
    metadata:
      labels:
        app: msvc-shoppingcart
    spec:
      containers:
        - image: carloshot007/msvc-shoppingcart:latest
          name: shoppingcart
          ports:
            - containerPort: 8002
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: msvc-shoppingcart
                  key: port
            - name: ACTIVEPROFILE
              valueFrom:
                configMapKeyRef:
                  name: msvc-shoppingcart
                  key: active_profile
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: msvc-shoppingcart
                  key: db_host
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: msvc-shoppingcart
                  key: database
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: msvc-shoppingcart
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: msvc-shoppingcart
                  key: password
            - name: MSVC_USERS_URL
              valueFrom:
                configMapKeyRef:
                  name: msvc-shoppingcart
                  key: msvc_users_url
            - name: MSVC_IMAGES_URL
              valueFrom:
                configMapKeyRef:
                  name: msvc-shoppingcart
                  key: msvc_images_url

---

apiVersion: v1
kind: Service
metadata:
  name: msvc-shoppingcart
spec:
  type: LoadBalancer
  ports:
    - port : 8002
      protocol: TCP
      targetPort: 8002
  selector:
    app: msvc-shoppingcart