apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-shoppingcart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-shoppingcart
  template:
    metadata:
      labels:
        app: msvc-shoppingcart
    spec:
      containers:
        - name: shoppingcart
          image: carloshot007/msvc-shoppingcart:latest
          ports:
            - containerPort: 8002
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: msvc-shoppingcart
                  key: port
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: msvc-shoppingcart
                  key: db_host
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: msvc-shoppingcart
                  key: database
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: msvc-shoppingcart
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: msvc-shoppingcart
                  key: password

---
apiVersion: v1
kind: Service
metadata:
  name: msvc-shoppingcart
spec:
  type: NodePort
  ports:
    - port : 8002
      protocol: TCP
      targetPort: 8002
      nodePort: 30086
  selector:
    app: msvc-shoppingcart