apiVersion: v1
kind: Service
metadata:
  name: msvc-shoppingcart
spec:
  type: LoadBalancer
  ports:
    - port : 8002
      protocol: TCP
      targetPort: 8002
  selector:
    app: msvc-shoppingcart